## An Introduction to Interactive Programming in Python
#### by Joe Warren, Scott Rixner, John Greiner, Stephen Wong
#### Rice University
***
This class consists of two parts that are five and four weeks long, respectively. For most weeks, you will watch two sets of videos (part a and part b) and then complete one quiz for each set. The main task for each week is to complete a mini-project that is due along with the quizzes early Sunday morning. You will then be asked to assess your peer's mini-projects on the following Sunday-Wednesday.


|Part           |       Week    |       Topics  |       Mini-project    |
|---------------| --------------| --------------| --------------------- |
|1 |	0 |	Statements, expressions, variables |	---|
|1 |	1 |	Functions, logic, conditionals |	"Rock-Paper-Scissors-Lizard-Spock" game|
|1 |	2 |	Event-driven programming, local and global variables, buttons and input fields |	"Guess the Number" game|
|1 |	3 |	The canvas, static drawing, timers, interactive drawing |	Stopwatch: The Game|
|1 |	4 |	Lists, keyboard input, motion, positional/velocity control |	"Pong" game|
|2 |	5 |	Mouse input, more lists, dictionaries, images |	"Memory" game|
|2 |	6 |	Classes, tiled images |	"Blackjack" game|
|2 |	7 |	Acceleration and friction, spaceship class, sprite class, sound |	Spaceship from "RiceRocks"| game
|2 |	8 |	Sets, groups of sprites, collisions, sprite animation |	Full "RiceRocks" game|

#### Note:
In order to run properly, all of the programs that were written for these Rice University Coursera courses need to be opened and run in CodeSkulptor (http://www.codeskulptor.org), which is a browser-based programming environment for the programming language Python that was developed by Prof. Scott Rixner at Rice University.
