## R Programming

#### by Roger D. Peng, Ph.D.
#### Johns Hopkins University
***
This is the 2nd course in Johns Hopkins University's Coursera Data Science Specialization.

Below is the course description. More information about the course and a verified certificate of course completion with distinction can be found [here](https://www.coursera.org/account/accomplishments/records/zMb3cXtC3UB4ACcJ).

#### Course Description

In this course you will learn how to program in R and how to use R for effective data analysis. You will learn how to install and configure software necessary for a statistical programming environment, discuss generic programming language concepts as they are implemented in a high-level statistical language. The course covers practical issues in statistical computing which includes programming in R, reading data into R, accessing R packages, writing R functions, debugging, and organizing and commenting R code. Topics in statistical data analysis and optimization will provide working examples.

#### Course Content

* Week 1: Overview of R, R data types and objects, reading and writing data
* Week 2: Control structures, functions, scoping rules, dates and times
* Week 3: Loop functions, debugging tools
* Week 4: Simulation, code profiling
