## Reproducible Research

#### by Roger D. Peng, Ph.D.
#### Johns Hopkins University
***
This is the 5th course in Johns Hopkins University's Coursera Data Science Specialization.

Below is the course description. More information about the course and a verified certificate of course completion with distinction can be found [here](https://www.coursera.org/account/accomplishments/records/MPWFpdtRSBnXeft5).

#### Course Description

In this course you will learn the ideas of reproducible research and reporting of statistical analyses. Topics covered include literate programming tools, evidence-based data analysis, and organizing data analyses. In this course you will learn to write a document using R markdown, integrate live R code into a literate statistical program, compile R markdown documents using knitr and related tools, publish reproducible documents to the web, and organize a data analysis so that it is reproducible and accessible to others.

#### Course Content

* Structuring and organizing a data analysis
* Markdown and R Markdown
* knitr / RPubs
* Reproducible research check list
* Evidence-based data analysis
* Case studies in air pollution epidemiology and high-throughput biology