## Exploratory Data Analysis

#### by Roger D. Peng, Ph.D.
#### Johns Hopkins University
***
This is the 4th course in Johns Hopkins University's Coursera Data Science Specialization.

Below is the course description. More information about the course and a verified certificate of course completion with distinction can be found [here](https://www.coursera.org/account/accomplishments/records/atNVNBt7FdfpFAFc).

#### Course Description

This course covers the essential exploratory techniques for summarizing data. These techniques are typically applied before formal modeling commences and can help inform the development of more complex statistical models. Exploratory techniques are also important for eliminating or sharpening potential hypotheses about the world that can be addressed by the data. We will cover in detail the plotting systems in R as well as some of the basic principles of constructing data graphics. We will also cover some of the common multivariate statistical techniques used to visualize high-dimensional data.

#### Course Content

* Making exploratory graphs
* Principles of analytic graphics
* Plotting systems and graphics devices in R
* The base, lattice, and ggplot2 plotting systems in R
* Clustering methods
* Dimension reduction techniques
